Êþº¾   ; r  Reparto_tuppers  java/lang/Object <init> ()V Code
  	   LineNumberTable LocalVariableTable this LReparto_tuppers; main ([Ljava/lang/String;)V  Distribuidora Tupperware@F€     @I      ?¾¸Që…¸  java/util/Scanner	    java/lang/System   in Ljava/io/InputStream;
  !  " (Ljava/io/InputStream;)V	  $ % & out Ljava/io/PrintStream; ( java/lang/StringBuilder * Costo por unidad:Q
 ' ,  - (Ljava/lang/String;)V
 ' / 0 1 append (D)Ljava/lang/StringBuilder;
 ' 3 4 5 toString ()Ljava/lang/String;
 7 9 8 java/io/PrintStream : - println < Cantidad de productos:Q
 ' > 0 ? (I)Ljava/lang/StringBuilder; A ------------------ C Total:Q E Venderse a :Q G Impuesto establecido :0.12 I Impuesto por unidad: Q?à      @!       O   Q $------------------------------------ S Cantidad vendida: U Total sin descuento:Q W IVA a declarar:Q Y  Tipo de descuento:Q [ Ganancia: Q args [Ljava/lang/String; nombreEmpresa Ljava/lang/String; costoUnitario D cantidadProductos I totalAPagar precioDeVenta IVA totalPorUnidadIVA entrada Ljava/util/Scanner; cantidadProductoVendido totalcobradoSinDescuento totalConDescuento impuestosADeclarar tipoDeDescuento 	ganancias 
SourceFile Reparto_tuppers.java !               /     *· ±    
                    	      †    `L I È6(‡k9 9 9	 k9» Y² ·  :² #» 'Y)· +(¶ .¶ 2¶ 6² #» 'Y;· +¶ =¶ 2¶ 6² #@¶ 6² #» 'YB· +¶ .¶ 2¶ 6² #» 'YD· +¶ .¶ 2¶ 6² #F¶ 6² #» 'YH· +¶ .¶ 2¶ 6<6‡k9 Jg9 c9 L9‡g9² #N¶ 6² #P¶ 6² #» 'YR· +¶ =¶ 2¶ 6² #» 'YT· +¶ .¶ 2¶ 6² #» 'YV· +¶ .¶ 2¶ 6² #» 'YX· +¶ .¶ 2¶ 6² #» 'YZ· +¶ .¶ 2¶ 6±    
   v        	         %  1  G  ^  f  }  ”  œ  ³  ·  ¿  Ç  Ï  Ô   Ü " ä # ì $ % &1 'H (_ +    ˜   ` \ ]   ] ^ _  Y ` a  T b c  M d a  H e a  C f a 	 %; g a  1/ h i  · © j c  ¿ ¡ k a  Ç ™ l a  Ï ‘ m a  Ô Œ n a  Ü „ o a   p    q